### ISSUE TITLE
Exercises - chapter 1 - question 3 duplicate entry

### ISSUE THREAD

**Issue by Zorry-Serafimova** [raptatinha/tau-introduction-to-playwright#23]
**🐞 Describe the question:**
The exercises for chapter1 question 3 have package-lock.json listed twice and I was wondering if one is possibly the package.json
**📸 Screenshots/GIFs/Videos:**
![Screenshot 2023-06-26 11 49 37 AM](https://github.com/raptatinha/tau-introduction-to-playwright/assets/51411436/6fe591a6-78c9-45ce-996f-d6c4b08679b3)

**Comment by Dksoni81291** [comment]
Yes, it should be package.json.
Also, you can check the folder structure post installation.!
