### ISSUE TITLE
Tests don't run 

### ISSUE THREAD

**Issue by veronmolosh** [raptatinha/tau-introduction-to-playwright#25]
**🐞 Describe the question:**
When I try to run tests with command npm run test:e2e:all, I receive an Error: Cannot find module 'dotenv'
I'm in chapter-2 branch

**📸 Screenshots/GIFs/Videos:**
![image](https://github.com/raptatinha/tau-introduction-to-playwright/assets/77335777/80964d8e-7ca8-4cd6-9533-32c50d331e38)

**🛝 Additional context:**
Add any other context here.

**🎡  A picture of your pet or a toy or something really cool:**

**Comment by raptatinha** [comment]
Hi @veronmolosh,
You need to install the 'dotenv' with `npm install` or `npm i`.
The full instructions are on the readme file: https://github.com/raptatinha/tau-introduction-to-playwright/blob/main/README.md
Give it a try and let me know if it works.
Thanks for getting in touch!

**Comment by veronmolosh** [comment]
Thanks! Now it works!
